version: '3'

services:
  db:
    image: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data
    restart: always
  web:
    build: .
    command: /code/start.sh
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
