# Generated by Django 2.0.2 on 2018-02-08 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20180207_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
